name: platon_codec
version: 2.0.0

dependencies:
  bech32: ^0.2.0
  convert: ^3.0.0
  pointycastle: ^3.6.2
  quiver: ^3.0.0
  ethereum_codec:
    git:
      url: https://github.com/nbltrust/dart-eth-transaction-codec
      ref: 2.0.0

dev_dependencies: 
  meta: ^1.3.0
  test: ^1.16.5

environment:
  sdk: ">=2.12.0 <3.0.0"
