name: platon_codec
version: 0.0.1

dependencies:
  bech32: ^0.1.2
  convert: ^2.1.1
  pointycastle: ^1.0.2
  quiver: ^2.1.5
  ethereum_util:
    git:
      url: https://github.com/ethereumdart/ethereum_util

dev_dependencies: 
  meta: 1.3.0
  test: 1.16.5

environment:
  sdk: ">=1.19.0 <3.0.0"
